package dev.laveenh.jazzanalyzer.storage;

import dev.laveenh.jazzanalyzer.config.JazzProperties;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.UUID;

/** Development storage: one file per upload in a local directory. Active unless the {@code s3} profile is on. */
@Component
@Profile("!s3")
public class LocalFileStorage implements FileStorage {

    private final Path directory;

    public LocalFileStorage(JazzProperties properties) {
        this.directory = properties.storage().localDir().toAbsolutePath().normalize();
        try {
            Files.createDirectories(directory);
        } catch (IOException e) {
            throw new StorageException("Cannot create storage directory " + directory, e);
        }
    }

    @Override
    public String store(byte[] content) {
        String key = UUID.randomUUID() + ".xml";
        try {
            Files.write(resolve(key), content);
        } catch (IOException e) {
            throw new StorageException("Cannot store file", e);
        }
        return key;
    }

    @Override
    public byte[] read(String key) {
        try {
            return Files.readAllBytes(resolve(key));
        } catch (NoSuchFileException e) {
            throw new StorageException("Stored file not found: " + key, e);
        } catch (IOException e) {
            throw new StorageException("Cannot read stored file " + key, e);
        }
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException e) {
            throw new StorageException("Cannot delete stored file " + key, e);
        }
    }

    /** Keys are generated by us, but never trust that: refuse anything that would leave the directory. */
    private Path resolve(String key) {
        Path path = directory.resolve(key).normalize();
        if (!path.startsWith(directory) || path.equals(directory)) {
            throw new StorageException("Invalid storage key");
        }
        return path;
    }
}
