-- Jazz chart analysis schema.
--
-- Deliberately has NO secondary indexes yet (only primary keys and the unique checksum).
-- Phase 4 measures the search query with EXPLAIN ANALYZE before and after adding indexes in V2,
-- so the "before" number has to come from an un-indexed schema.

CREATE TABLE songs (
    id                UUID PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,   -- shown to users, never used as a path
    storage_key       VARCHAR(255) NOT NULL,   -- generated by us, e.g. <uuid>.xml
    checksum_sha256   VARCHAR(64)  NOT NULL UNIQUE CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),   -- SHA-256 hex; same file twice = same song
    uploaded_at       TIMESTAMPTZ  NOT NULL
);

CREATE TABLE analyses (
    id            UUID PRIMARY KEY,
    song_id       UUID        NOT NULL REFERENCES songs (id) ON DELETE CASCADE,
    status        VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETE', 'FAILED')),
    detected_key  VARCHAR(32),                 -- main key, e.g. 'Bb major'
    created_at    TIMESTAMPTZ NOT NULL,
    completed_at  TIMESTAMPTZ,
    error_message TEXT
);

CREATE TABLE key_regions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id    UUID          NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    position_index INT           NOT NULL,     -- order of the region within the tune
    key_name       VARCHAR(32)   NOT NULL,
    start_measure  INT           NOT NULL,
    end_measure    INT           NOT NULL,
    confidence     DOUBLE PRECISION NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    reason         TEXT          NOT NULL
);

CREATE TABLE chords (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id     UUID          NOT NULL REFERENCES analyses (id) ON DELETE CASCADE,
    position_index  INT           NOT NULL,    -- order of the chord within the tune
    measure         INT           NOT NULL,
    beat            DOUBLE PRECISION NOT NULL,
    symbol          VARCHAR(48)   NOT NULL,
    root_pc         SMALLINT      NOT NULL CHECK (root_pc BETWEEN 0 AND 11),   -- pitch class: 0 = C
    quality         VARCHAR(32)   NOT NULL,    -- ChordQuality enum name, e.g. MINOR7
    roman_numeral   VARCHAR(48)   NOT NULL,
    chord_function  VARCHAR(32)   NOT NULL,    -- ChordFunction enum name ('function' is an SQL keyword)
    function_reason TEXT          NOT NULL,
    local_key       VARCHAR(32)   NOT NULL
);

CREATE TABLE scale_suggestions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chord_id    BIGINT       NOT NULL REFERENCES chords (id) ON DELETE CASCADE,
    rank        SMALLINT     NOT NULL,         -- 1 = first choice
    scale_name  VARCHAR(64)  NOT NULL,         -- e.g. 'D Dorian'
    scale_notes VARCHAR(64)  NOT NULL,         -- spelled notes, e.g. 'D E F G A B C'
    reason      TEXT         NOT NULL
);
